name: Publish to Docker
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: opcruz
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: opcruz/simple-java-server
          tag_with_sha: true
